version: "3.9"
services:
  transcoder:
    build: .
    image: streamhive/transcoder:dev
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - AMQP_EXCHANGE=streamhive
      - AMQP_UPLOAD_ROUTING_KEY=video.uploaded
      - AMQP_TRANSCODED_ROUTING_KEY=video.transcoded
      - AMQP_QUEUE=transcoder.video.uploaded
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - AZURE_BLOB_CONTAINER=uploadservicecontainer
      - CONCURRENCY=1
    depends_on:
      - rabbitmq
    networks:
      - core
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [core]
networks:
  core: {}
